module.exports = mongoose => {
    var schema = mongoose.Schema(
      {
        domain: String,
        source: String,
        source_type: String,
        tf: String,
        tf_link: String,
        cf: String,
        maj_bl: String,
        maj_rd: String,
        maj_topics: String,
        maj_lang: String,
        site_lang: String,
        moz_da: String,
        moz_pa: String,
        age: String,
        sz_score: String,
        sz_redirects: String,
        sz_parked: String,
        sz_ahistory: String,
        sz_drops: String,
        google_index: String,
        outlinks_internal: String,
        outlinks_external: String,
        outdomains_external: String,
        sem_traf: String,
        sem_rank: String,
        sem_kw: String,
        date_added: String,
        price: String,
        expires: String,
        main_section: String,
        archives: String,
        backlinks: String,
        anchors: String,
        titles: String,
        redirects: String,
        wordcounts: String,
        majestics: String,
        domain_drops: String,
        google_index_html: String,
        ranking_keywords_html: String,
        langs_html: String,
        whois_histories: String,
      },
      { timestamps: true }
    );
    const Spamzilla = mongoose.model("spamzilla", schema);
    return Spamzilla;
  };